#!/bin/bash

if [[ $1 == "parse" ]]; then
  packet=""
  capturing=""
  count=0

  
  ####completion flags
  a=0  #completion flag for mint
  b=0  #completion flag for blueberry
  c=0  #completion flag for coconut
  d=0  #completion flag for icy
  e=0  #completion flag for beetroot
  f=0  #completion flag for lemon2
  g=0  #completion flag for coconut2
  h=0  #completion flag for candy2
  count=0 #counter for number of data received


  #### arrays for each beacon's information
  mint=()
  blueberry=()
  coconut=()
  icy=()
  beetroot=()
  lemon2=()
  coconut2=()
  candy2=()


  while read line && [[ $counter -lt 300 ]]
  do
    count=$[count + 1]
    if [ "$capturing" ]; then
      if [[ $line =~ ^[0-9a-fA-F]{2}\ [0-9a-fA-F] ]]; then
        packet="$packet $line"
      else
        if [[ $packet =~ ^04\ 3E\ 2A\ 02\ 01\ .{26}\ 02\ 01\ .{14}\ 02\ 15 ]]; then
          UUID=`echo $packet | sed 's/^.\{69\}\(.\{47\}\).*$/\1/'`
          MAJOR=`echo $packet | sed 's/^.\{117\}\(.\{5\}\).*$/\1/'`
          MINOR=`echo $packet | sed 's/^.\{123\}\(.\{5\}\).*$/\1/'`
          POWER=`echo $packet | sed 's/^.\{129\}\(.\{2\}\).*$/\1/'`
          UUID=`echo $UUID | sed -e 's/\ //g' -e 's/^\(.\{8\}\)\(.\{4\}\)\(.\{4\}\)\(.\{4\}\)\(.\{12\}\)$/\1-\2-\3-\4-\5/'`
          MAJOR=`echo $MAJOR | sed 's/\ //g'`
          MAJOR=`echo "ibase=16; $MAJOR" | bc`
          MINOR=`echo $MINOR | sed 's/\ //g'`
          MINOR=`echo "ibase=16; $MINOR" | bc`
          POWER=`echo "ibase=16; $POWER" | bc`
          POWER=$[POWER - 256]
          RSSI=`echo $packet | sed 's/^.\{132\}\(.\{2\}\).*$/\1/'`
          RSSI=`echo "ibase=16; $RSSI" | bc`
          RSSI=$[RSSI - 256]
          


          #FOR MINT
          if [ "$UUID" = "B9407F30-F5F8-466E-AFF9-25556B57FE6D" -a "$MAJOR" = "13184" -a "$MINOR" = "55684" -a $a == 0 ]; then
            
            if [[ $2 == "-csv" ]]; then
            #echo "NAME: 'MINT/LIGHTGREEN'     RSSI: $RSSI   $(date -u)"
            mint=($RSSI)
            else
            mint=(1 $RSSI $(date -u)) #array of ID, corresponding RSSI and timestamp
            fi

            a=$[a + 1]

          fi
          
          #FOR BLUEBERRY
          if [ "$UUID" = "B9407F30-F5F8-466E-AFF9-25556B57FE6D" -a "$MAJOR" = "17050" -a "$MINOR" = "26873" -a $b == 0 ]; then
            
            if [[ $2 == "-csv" ]]; then
            blueberry=($RSSI)
            else
            blueberry=(2 $RSSI $(date -u)) #array of ID, corresponding RSSI and timestamp
            fi

            b=$[b + 1]
          fi

          #FOR COCONUT PUFF
          if [ "$UUID" = "B9407F30-F5F8-466E-AFF9-25556B57FE6D" -a "$MAJOR" = "21506" -a "$MINOR" = "34046" -a $c == 0 ]; then

            if [[ $2 == "-csv" ]]; then
            coconut=($RSSI)
            else
            coconut=(3 $RSSI $(date -u)) #array of ID, corresponding RSSI and timestamp
            fi

            c=$[c + 1]
          fi


          #FOR ICY
          if [ "$UUID" = "B9407F30-F5F8-466E-AFF9-25556B57FE6D" -a "$MAJOR" = "11993" -a "$MINOR" = "38783" -a $d == 0 ]; then
            
            if [[ $2 == "-csv" ]]; then
            icy=($RSSI)
            else
            icy=(4 $RSSI $(date -u)) #array of ID, corresponding RSSI and timestamp
            fi
            
            d=$[d + 1]
          fi


          #FOR BEETROOT
          if [ "$UUID" = "B9407F30-F5F8-466E-AFF9-25556B57FE6D" -a "$MAJOR" = "30174" -a "$MINOR" = "30511" -a $e == 0 ]; then
            
            if [[ $2 == "-csv" ]]; then
            beetroot=($RSSI)
            else
            beetroot=(4 $RSSI $(date -u)) #array of ID, corresponding RSSI and timestamp
            fi
            
            e=$[e + 1]
          fi


          #FOR LEMON2
          if [ "$UUID" = "B9407F30-F5F8-466E-AFF9-25556B57FE6D" -a "$MAJOR" = "30174" -a "$MINOR" = "8113" -a $f == 0 ]; then
            
            if [[ $2 == "-csv" ]]; then
            lemon2=($RSSI)
            else
            lemon2=(4 $RSSI $(date -u)) #array of ID, corresponding RSSI and timestamp
            fi
            
            f=$[f + 1]
          fi


          #FOR COCONUT2
          if [ "$UUID" = "B9407F30-F5F8-466E-AFF9-25556B57FE6D" -a "$MAJOR" = "30174" -a "$MINOR" = "5667" -a $g == 0 ]; then
            
            if [[ $2 == "-csv" ]]; then
            coconut2=($RSSI)
            else
            coconut2=(4 $RSSI $(date -u)) #array of ID, corresponding RSSI and timestamp
            fi
            
            g=$[g + 1]
          fi

          #FOR CANDY2
          if [ "$UUID" = "B9407F30-F5F8-466E-AFF9-25556B57FE6D" -a "$MAJOR" = "30174" -a "$MINOR" = "31621" -a $h == 0 ]; then
            
            if [[ $2 == "-csv" ]]; then
            candy2=($RSSI)
            else
            candy2=(4 $RSSI $(date -u)) #array of ID, corresponding RSSI and timestamp
            fi
            
            h=$[h + 1]
          fi

          #WRITING INTO TXT FILE // TO BE CONVERTED TO CSV FILE
          if [  $a -gt 0 -a  $b -gt 0 -a $c -gt 0 -a $d -gt 0 -a $e -gt 0 -a $f -gt 0 -a $g -gt 0 -a $h -gt 0 ]; then
            
            if [[ $2 == "-csv" ]]; then
            echo "${mint[@]},${blueberry[@]},${coconut[@]},${icy[@]},${beetroot[@]},${lemon2[@]},${coconut2[@]},${candy2[@]},$3" && echo 
            "${mint[@]},${blueberry[@]},${coconut[@]},${icy[@]},${beetroot[@]},${lemon2[@]},${coconut2[@]},${candy2[@]},$3" >> $4
            else
            echo ${mint[@]} && echo ${mint[@]} >> data.txt
            echo ${blueberry[@]} && echo ${blueberry[@]} >> data.txt
            echo ${coconut[@]} && echo ${coconut[@]} >> data.txt
            echo ${icy[@]} && echo ${icy[@]} >> data.txt
            echo ${beetroot[@]} && echo ${beetroot[@]} >> data.txt
            echo ${lemon2[@]} && echo ${lemon2[@]} >> data.txt
            echo ${coconut2[@]} && echo ${coconut2[@]} >> data.txt
            echo ${candy2[@]} && echo ${candy2[@]} >> data.txt
            echo && echo >> data.txt
            fi
            #echo & update counter
            echo "COUNTER: $counter"
            counter=$[counter + 1]
            #clear flags
            a=0
            b=0
            c=0
            d=0
            e=0
            f=0
            g=0
            h=0
          fi

        fi
        capturing=""
        packet=""
      fi
    fi



    if [ ! "$capturing" ]; then
      if [[ $line =~ ^\> ]]; then
        packet=`echo $line | sed 's/^>.\(.*$\)/\1/'`
        capturing=1
      fi
    fi
  done


else
  sudo hcitool lescan --duplicates 1>/dev/null &
  if [ "$(pidof hcitool)" ]; then
    sudo hcidump --raw | ./$0 parse $1 $2 $3 $4
  fi
fi
