#!/bin/bash

if [[ $1 == "parse" ]]; then
  packet=""
  capturing=""
  count=0
  

  while read line
  do
    count=$[count + 1]
    if [ "$capturing" ]; then
      if [[ $line =~ ^[0-9a-fA-F]{2}\ [0-9a-fA-F] ]]; then
        packet="$packet $line"
      else
        if [[ $packet =~ ^04\ 3E\ 2A\ 02\ 01\ .{26}\ 02\ 01\ .{14}\ 02\ 15 ]]; then
          UUID=`echo $packet | sed 's/^.\{69\}\(.\{47\}\).*$/\1/'`
          MAJOR=`echo $packet | sed 's/^.\{117\}\(.\{5\}\).*$/\1/'`
          MINOR=`echo $packet | sed 's/^.\{123\}\(.\{5\}\).*$/\1/'`
          POWER=`echo $packet | sed 's/^.\{129\}\(.\{2\}\).*$/\1/'`
          UUID=`echo $UUID | sed -e 's/\ //g' -e 's/^\(.\{8\}\)\(.\{4\}\)\(.\{4\}\)\(.\{4\}\)\(.\{12\}\)$/\1-\2-\3-\4-\5/'`
          MAJOR=`echo $MAJOR | sed 's/\ //g'`
          MAJOR=`echo "ibase=16; $MAJOR" | bc`
          MINOR=`echo $MINOR | sed 's/\ //g'`
          MINOR=`echo "ibase=16; $MINOR" | bc`
          POWER=`echo "ibase=16; $POWER" | bc`
          POWER=$[POWER - 256]
          RSSI=`echo $packet | sed 's/^.\{132\}\(.\{2\}\).*$/\1/'`
 		  RSSI=`echo "ibase=16; $RSSI" | bc`
 		  RSSI=$[RSSI - 256]
          



          if [[ $2 == "-b" ]]; then
	    	echo "$UUID $MAJOR $MINOR $POWER $RSSI"
          
          
          elif [[ $2 == "-readall" ]]; then
          	##FOR ICY
	          	if [ "$UUID" = "B9407F30-F5F8-466E-AFF9-25556B57FE6D" -a "$MAJOR" = "11993" -a "$MINOR" = "38783" ]; then
	    	    echo "NAME: 'ICY/LIGHTBLUE'			RSSI: $RSSI		$(date -u)"
	    		fi

    		#FOR MINT
    		if [ "$UUID" = "B9407F30-F5F8-466E-AFF9-25556B57FE6D" -a "$MAJOR" = "13184" -a "$MINOR" = "55684" ]; then
    	    echo "NAME: 'MINT/LIGHTGREEN'			RSSI: $RSSI		$(date -u)"
    		fi
    		
    		#FOR BLUEBERRY
    		if [ "$UUID" = "B9407F30-F5F8-466E-AFF9-25556B57FE6D" -a "$MAJOR" = "17050" -a "$MINOR" = "26873" ]; then
    	    echo "NAME: 'BLUEBERRY/PURPLE'		RSSI: $RSSI		$(date -u)"
    		fi

    		#FOR COCONUT PUFF
    		if [ "$UUID" = "B9407F30-F5F8-466E-AFF9-25556B57FE6D" -a "$MAJOR" = "21506" -a "$MINOR" = "34046" ]; then
    	    echo "NAME: 'COCONUT/WHITE'			RSSI: $RSSI		$(date -u)"
    		fi

    		#echo
          elif [[ $2 == "-icy" ]]; then
	        if [ "$UUID" = "B9407F30-F5F8-466E-AFF9-25556B57FE6D" -a "$MAJOR" = "11993" -a "$MINOR" = "38783" ]; then
	    	echo "NAME: 'ICY/LIGHTBLUE'				RSSI: $RSSI		$(date -u)"
	    	fi

          elif [[ $2 == "-mint" ]]; then
    		if [ "$UUID" = "B9407F30-F5F8-466E-AFF9-25556B57FE6D" -a "$MAJOR" = "13184" -a "$MINOR" = "55684" ]; then
    	    echo "NAME: 'MINT/LIGHTGREEN'			RSSI: $RSSI		$(date -u)"
    		fi  

          elif [[ $2 == "-blueberry" ]]; then
    		if [ "$UUID" = "B9407F30-F5F8-466E-AFF9-25556B57FE6D" -a "$MAJOR" = "17050" -a "$MINOR" = "26873" ]; then
    	    echo "NAME: 'BLUEBERRY/PURPLE'		RSSI: $RSSI		$(date -u)"
    		fi
          
          elif [[ $2 == "-coconut" ]]; then
    		if [ "$UUID" = "B9407F30-F5F8-466E-AFF9-25556B57FE6D" -a "$MAJOR" = "21506" -a "$MINOR" = "34046" ]; then
    	    echo "NAME: 'COCONUT/WHITE'			RSSI: $RSSI		$(date -u)"
    		fi

          else
    	    echo "UUID: $UUID MAJOR: $MAJOR MINOR: $MINOR POWER: $POWER RSSI: $RSSI"
          fi

        fi
        capturing=""
        packet=""
      fi
    fi

    if [ ! "$capturing" ]; then
      if [[ $line =~ ^\> ]]; then
        packet=`echo $line | sed 's/^>.\(.*$\)/\1/'`
        capturing=1
      fi
    fi
  done


else
  sudo hcitool lescan --duplicates 1>/dev/null &
  if [ "$(pidof hcitool)" ]; then
    sudo hcidump --raw | ./$0 parse $1
  fi
fi
